title:            Tibet Support Groep Nederland
acronym:          TSG-NL
description:      We are all about Tibet, Human Rights, Action.
logo:             omikron.png

baseurl: /tibetnujekyll

collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title.html
  authors:
    output: true
  news:
    output: true
  events:
    output: true

# theme:            jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

notification:
  show: true
  message: "Belangrijke aankondiging: Sluit je aan bij onze nieuwe campagne!"
  link_url: "/kom-in-actie/nieuwe-campagne/"
  link_text: "Lees meer"


home:
  title: "Tibet Support Groep Nederland"
  hero_background: "/assets/images/hero-background.jpg"
  description: "We are all about Tibet, Human Rights, Action."

  image: "omikron.png"
  call_to_action:
    text: "Join us"
    url: "/join-us/"