title:            Tibet Support Groep Nederland
acronym:          TSG-NL
description:      We are all about Tibet, Human Rights, Action.
logo:             omikron.png

baseurl: /tibetnujekyll

collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title.html
  authors:
    output: true
  news:
    output: true

theme:            jekyll-theme-minimal




